apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo-app
spec:
  type: ClusterIP
  selector:
    name: demo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080